### ISSUE TITLE
i18next style string interpolation causes an error

### ISSUE THREAD

**Issue by djensen47** [leolabs/json-autotranslate#1]
If I have a string value that uses i18next interpolation, such as:

`"I am {{author.name}}"`

then I get the following error:

```
An error has occured:
Expected identifier but "{" found.
SyntaxError: Expected identifier but "{" found.
```

---

BTW, thanks for building this, it's super useful!

**Comment by djensen47** [comment]
Turns out that if I change `{{` to `{` then it works.

**Comment by djensen47** [comment]
However, I get the same issue if I'm using i18next nesting `$(key)` or `$({{keyInTheVar}})`

**Comment by leolabs** [comment]
Hey @djensen47, thanks for the issue!

Could you provide a sample JSON file and the command you used to run json-autotranslate, so I can try to reproduce it on my side? My guess is that the ICU-format parser doesn't like i18next's syntax. I could add a flag to switch between ICU-style and i18next-style interpolation.

**Comment by djensen47** [comment]
This is what I have in my file. I don't use the `$t(key)` syntax but I do use the `$t({{keyInTheVar}})` syntax. But you should definitely handle both.

```
{
  "errorMessages": {
    "formErrors": "Please fix the errors in the form and try again.",
    "invalid-login": "Invalid email address or password",
    "number": "${$displayName} must be a number"
  },
  "message": {
    "confirm-delete-instruction": "Are you sure you want to delete the instruction, \"{{name}}\"?"
  },
  "label": {
    "pricePerUnit": "Price per $t({{unitKey}})"
  }
}
```

**Comment by leolabs** [comment]
I've released a new version that supports ICU as well as i18next and sprintf-style interpolations. You can select the interpolation matcher using the `-m` flag (e.g. `-m i18next` in your case). I'd be happy to hear if this works for you :)

**Comment by djensen47** [comment]
For some reason npm install isn't working after the update. Not sure if it's "just me" yet or not.

**Comment by leolabs** [comment]
Hmm, that's weird. I'll check it on my side as well. Can you provide the npm error you get when you try to run json-autotranslate?

**Comment by djensen47** [comment]
```
npm ERR! path /src/node_modules/json-autotranslate/lib/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/src/node_modules/json-autotranslate/lib/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by djensen47** [comment]
I'm running node 8.14.0 but it also happens on 6.

I confirmed that the problem is happening on two different machines.

**Comment by djensen47** [comment]
After  I use yarn to install, there's a similar issue. Under node_modules/json-autotranslate there are no source files.

It's like the last push to npm and yarn didn't succeed?

**Comment by leolabs** [comment]
You were right. The build somehow failed on GitHub Actions. I've fixed that and everything should work as expected again.

**Comment by djensen47** [comment]
Works great now. Thanks!
