### ISSUE TITLE
Readme Issues

### ISSUE THREAD

**Issue by digitalcoyote** [leolabs/json-autotranslate#112]
I noticed a couple of issues in the readme and I'd be willing to put in a PR if you'd prefer:

- Under the Key-Based header: 
  - the example option is `--type keybased` but it appears the correct usage is `--type key-based`
- Under the Azure Translator Text header:
  -  it seems to imply the region is optional, but I wasn't able to successfully run without providing a region.
  - There is no link to the Azure pricing as there is with Amazon Translate
    - https://azure.microsoft.com/en-us/pricing/details/cognitive-services/translator/
- Invalid Keys
  - There are no mentions on the ReadMe of what makes a key invalid. Keys with `.` or whitespace are valid in i18next files but not supported by json-autotranslate so this information would be helpful for troubleshooting.

Love the tool, it saved me a chunk of time with very little modification to our project (we weren't going to automate translations without some refactoring anyway).

**Comment by leolabs** [comment]
Hey @digitalcoyote, thank you so much for your feedback! I'd be happy to merge your PR if you're okay with creating one. Otherwise I can also fix these mistakes myself :)

**Comment by digitalcoyote** [comment]
It's either way for me. I'll prep a PR tonight, but if the mood takes you, go ahead and fix it 🙂

**Comment by digitalcoyote** [comment]
Opened a PR #113 

I made the Readme changes on my phone, so you may want to double check the layout on a wider screen. I'll try to double back tomorrow when I have time.
