### ISSUE TITLE
Unable to translate to traditional chinese with Google translate. 

### ISSUE THREAD

**Issue by melonpandev** [leolabs/json-autotranslate#18]
According to [this page](https://cloud.google.com/translate/docs/languages) traditional Chinese is supported in the Google translate API. 

So in theory with a folder named zh-TW it should give a translation. 
![image](https://user-images.githubusercontent.com/20312733/78862189-1da25c80-7a7a-11ea-8a52-e9fc94b36683.png)

When using a folder named zh-tw, it gives a error that indicates an invalid language on google API's end.
![image](https://user-images.githubusercontent.com/20312733/78862314-6c4ff680-7a7a-11ea-94de-3bceb41ea0b8.png)

**Comment by leolabs** [comment]
I'll have a look at that today. It seems that the language codes are case-sensitive, so I'll have to convert them from `zh-tw` to `zh-TW`. Should be easy to do.
