### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by djensen47** [leolabs/json-autotranslate#2]
Sorry, I wasn't sure the best way to send you some questions about the library ...

1. I'm seeing something where a phrase like "Hop Farm" does not get translated but "Hop farm" does get translated properly. I don't really have any proper nouns in my translation file. Is there any way to force the translation to always translate uppercase words?

2. The word "hops" and "hop" is particularly troublesome.  In my context I'm referring to the ingredient used in beer: _lúpulo, hopfen, houblon_. Aside from interpolation, is there a way to force the translator to prefer one translation of a word over another?

**Comment by djensen47** [comment]
Looks like the answer is no on both of these.

**Comment by leolabs** [comment]
You're correct. I have no control over how the translation APIs treat the texts. You could try using the DeepL API and see if it returns better results. It'll cost, however, about $5 per month iirc.
