### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by pgmade** [leolabs/json-autotranslate#22]
After install i have some problem:

![Снимок экрана 2020-04-27 в 23 08 07](https://user-images.githubusercontent.com/9200326/80415976-02d64180-88dc-11ea-8395-8cd99a098497.png)

Can you tell me what the problem is?

**Comment by leolabs** [comment]
Hey @pgmade,
as stated in the error message, json-autotranslate can't find the folder that contains your source language files. The default source language is `en` and can be changed using the `-l` flag. If you don't specify an input directory using the `-i` flag, the tool looks for the `en` folder in the current working directory.

Please consult the [README](https://github.com/leolabs/json-autotranslate#json-autotranslate) for further information on how to properly configure json-autotranslate.

Let me know if you have any further questions :)

**Comment by leolabs** [comment]
I'll close this one as inactive.
