### ISSUE TITLE
i18next - Interpolation throwing partial errors

### ISSUE THREAD

**Issue by gtconsulting** [leolabs/json-autotranslate#23]
@leolabs  It seems there are some issues in supporting the interpolations. It's working well in some places but it's considering for translations at some other places. It's completely random. Find the example here. 

I have a key: value like this -> "title": "{{underlying_asset}}-{{quoting_asset}} Index"

After converting it to Arabic, the result is: "title": "\<span\>\<span\>0-1\</span\>\</span\> مؤشر"

Ideally, it shouldn't ignore those keys underlying_asset, quoting_asset

**Comment by leolabs** [comment]
Hey @gtconsulting,

that sounds like a bug, it shouldn't happen that way. Could you clarify which service you're using for translation? I'll take a look into it then :)

**Comment by gtconsulting** [comment]
@leolabs  Thanks for the quick response. I am using the default service. google-translate

**Comment by gtconsulting** [comment]
@leolabs  Any update on this?

**Comment by alexandrehpiva** [comment]
Same problem here. Im using i18next and the interpolation is with two curly braces:

`{
  "example": "Example {{number}}"
}`

I'm trying to use manual translations and running:

`json-autotranslate -i public/locales -s manual --type keybased`

i get: "Expected identifier but "{" found."

**Comment by leolabs** [comment]
@alexandrehpiva in your case, you just need to add the `-m i18next` flag to your command so json-autotranslate to make it work :)

**Comment by alexandrehpiva** [comment]
Thx man, very nice lib
