### ISSUE TITLE
Update cache with already translated key-value pairs

### ISSUE THREAD

**Issue by alexandrehpiva** [leolabs/json-autotranslate#25]
I'm migrating from intl to i18next and using json-autotranslate to add new translations. When i run script to generate new translations:

`json-autotranslate -i public/locales -s manual --type keybased -l en`

It asking for the already existing key-value pairs in all files (the cache is not updated, i think).

There is a way to update cache with already translated key-value pairs in all files?

Id like this feature because i add .json-autotranslate-cache/ to .gitignore and the idea is run something like 'json-autotranslate -updatecache' to verify and update the local cache before run the generate translations script.

**Comment by leolabs** [comment]
Hmm, that shouldn't happen either way. I'll take a look at it tomorrow :)

**Comment by alexandrehpiva** [comment]
It is not asking for the already existing key-value pairs anymore. Some pull requests must have fixed. Thanks!
