### ISSUE TITLE
Azure requires region

### ISSUE THREAD

**Issue by ultamatt** [leolabs/json-autotranslate#30]
Tried this great library out with Azure and they need a region. I monkied with the js on my node_module and it works by adding the extra header item. 

https://github.com/leolabs/json-autotranslate/blob/0fd6d1c1c91e079b1cb6ac21666fba9acbd99559/src/services/azure-translator.ts#L81

https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-reference#authenticating-with-a-regional-resource

**Comment by leolabs** [comment]
Thanks for the report, @ultamatt!

I'll add it in this week :)

**Comment by leolabs** [comment]
Thank you so much for the donation 💙
