### ISSUE TITLE
source language en doesnt exist

### ISSUE THREAD

**Issue by techmastersri** [leolabs/json-autotranslate#32]
I created the directory localed added subfolders of languages I want to translate en to, inside en folder I have my source json file that needs translating, I'm using deepl which I did signed up with

![image](https://user-images.githubusercontent.com/17889431/95045483-5de83d80-069f-11eb-81e7-f34db33c5187.png)

**Comment by leolabs** [comment]
Hey @techmastersri,

could you post the command you used to run json-autotranslate? If you do, you can replace your API key with a placeholder. My guess is that json-autotranslate is looking for language folders in the wrong directory.

**Comment by sr258** [comment]
This might be late, but maybe someone else benefits from it: Possibly, you execute the program with `npm start --your-options...`. It should be `npm start -- --your-options`.

**Comment by leolabs** [comment]
Thanks, that's a good tip! :)
