### ISSUE TITLE
Does not translate to French.

### ISSUE THREAD

**Issue by kernelogic** [leolabs/json-autotranslate#37]
I ran command json-autotranslate -f -i locales -m i18next -c .\grand-store-292020-1d6d5dbdee41.json and this is what I got.
My french json has all keys but no values.

Found 1 target language(s):
-> fr

🏭 Loading source files...
├── translation.json (natural)
└── Done

🔍 Looking for key-value inconsistencies in source files...
└── No inconsistencies found

🔍 Looking for invalid keys in source files...
└── No invalid keys found

💬 Translating strings from en to fr...
├── Translating translation.json (0 changes from cache) (+0)
└── All strings have been translated.

🗂 Caching source translation files...
└── Translation files have been cached.

0 new translations have been added!

**Comment by kernelogic** [comment]
I just tried manual too, seems it does not recognize any key

json-autotranslate -f -l en -s manual -i locales -m i18next -t natural
Found 1 target language(s):
-> fr

🏭 Loading source files...
├── translation.json (natural)
└── Done

✨ Initializing Manual Translation...
└── Done

🔍 Looking for key-value inconsistencies in source files...
└── No inconsistencies found

🔍 Looking for invalid keys in source files...
└── No invalid keys found

💬 Translating strings from en to fr...
├── Translating translation.json (0 changes from cache) (+0)
└── All strings have been translated.

🗂 Caching source translation files...
└── Translation files have been cached.

0 new translations have been added!

**Comment by leolabs** [comment]
Thanks for the bug report! Could you show me what your `en` folder looks like? I've been trying to reproduce it on my side, but everything seems to work as expected.

**Comment by kernelogic** [comment]
Hi, so I have the following structure:
locales/en/translation.json
locales/fr/translation.json

Initially the two json files have identical content:
{
  "Please try it again later.": ""
}

After I run the command, locales/en/translation.json content becomes
{
  "Please try it again later.": "Please try it again later."
}
Which is correct. However the locales/fr/translation.json remain as 
{
  "Please try it again later.": ""
}
I expected it to be containing a french translation.

**Comment by leolabs** [comment]
Ah, I think there lies the problem. When you remove the key from the file in `fr`, or remove the file altogether, it should work as expected. This tool won't touch existing keys because it doesn't know whether you've already modified the translation yourself :)

**Comment by kernelogic** [comment]
Aha thank you so much. That saved my day.
After I replace the french translation.json with an empty {} it worked!

**Comment by leolabs** [comment]
Awesome, that's good to hear! Feel free to let me know if you have any other issues or questions regarding json-autotranslate :)
