### ISSUE TITLE
Google Translator oddities

### ISSUE THREAD

**Issue by sr258** [leolabs/json-autotranslate#41]
When using the tool with Google Translator and i18next interpolation (using {{placeholder}}), there are cases in which google translate put strings into the <span>0</span> tag passed to Google Translate.

Example: Google translate returns
``
Det uppstod ett fel när filen <span>0 skulle</span> raderas från innehållsobjektet.
``
instead of 

``Det uppstod ett fel när filen <span>0</span> raderas från innehållsobjektet.``

It looks like the translator tries to make sense of the sentence by putting in words inside the span. You can prevent this behavior by adding a `translate="no"` atribute to the span like this in `src/matchers/index.ts`:

```
export const xmlStyleReplacer = (index: number) => `<span translate="no">${index}</span>`;
```

I haven't submitted a PR on this, as I'm unsure if this will break other translators. Maybe you need a Google Translate specific replacer...

Another thing I've noticed is that Google Translate escapes all characters considered unsafe in HTML. So an apostrophe become &#39;. It would be great if the json-autotranslate decodes these characters back to their actual value. It might be worth adding an option for this, as source strings might already contain HTML encoded characters.

**Comment by leolabs** [comment]
Hey @sr258!

Thanks so much for looking into this! I've gotten a similar request for the Azur Translator that also included a `translate="no"` fix suggestion, so it should be fine. Regarding the escaping of characters, does this happen consistently? If so, I'd just enable decoding for responses from Google.

Best,
Leo
