### ISSUE TITLE
Doesn't work with the new "DeepL Free plan"

### ISSUE THREAD

**Issue by bmikaeli** [leolabs/json-autotranslate#45]
Looks like the API endpoint need to be changed from 

var API_ENDPOINT = 'https://api.deepl.com/v2';
to 
var API_ENDPOINT = 'https://api-free.deepl.com/v2';

when using a free plan.  

(I guess that's a new plan on deepL, I didn't saw it before )

maybe we should have a service "deepl-pro" or "deepl-free" ?

**Comment by leolabs** [comment]
That sounds like a good idea! Is this something you'd like to implement or do you want me to take a look at it? :)

**Comment by bmikaeli** [comment]
I'm not sure to have the time to do it right now, if you can have to have a look, go for it !

It's not urgent at all, I just thought it was something you would like to be informed :)

**Comment by leolabs** [comment]
This was implemented in #50 :)
