### ISSUE TITLE
When files do not exist in 'destination' language, vague error is thrown 

### ISSUE THREAD

**Issue by ultamatt** [leolabs/json-autotranslate#46]
Line 388 here will error with a vague '.name doesn't exist' error when I have a 'help.json' file in my 'en' directory, but 'help.json' does not exist in my de directory. 

![image](https://user-images.githubusercontent.com/2548904/117473320-ae15cf80-af0e-11eb-8d0c-60b212a50152.png)

After looking through your source, I understood what was going on and made those files by hand, but a clearer error message might be helpful.

Thank you for the library! It's been very useful and saved me hours of my life. I hope you're well!

**Comment by sostenesg7** [comment]
I'm facing the same problem. The workaround is create all target lang files manually

**Comment by leolabs** [comment]
Sorry for the late reply! This shouldn't happen, I'll look into it tonight and see if I can fix it. There's also #48 which could be the solution to this issue.
