### ISSUE TITLE
Support for DeepL Free API

### ISSUE THREAD

**Issue by GregoryWullimann** [leolabs/json-autotranslate#49]
Hi,

it looks like only the Pro DeepL version is supported, since the API request is made to the PRO endpoint. Could you add a parameter to support the free version as well (without Pro you have 500'000 characters/month).

Example to get all languages: `https://api-free.deepl.com/v2/languages` instead of `https://api.deepl.com/v2/languages`

https://github.com/leolabs/json-autotranslate/blob/d8d7ab7839b5c6ce94a0f9a4bd88e2d569033030/src/services/deepl.ts#L11

**Comment by leolabs** [comment]
Thanks for your feature request! The same was also requested in #45. I'll see if I can implement it this week :)

**Comment by GregoryWullimann** [comment]
Oh sorry, don't know how I missed it! Will close this issue then.

Thanks

**Comment by leolabs** [comment]
No worries :)
