### ISSUE TITLE
Add command to change a key

### ISSUE THREAD

**Issue by djensen47** [leolabs/json-autotranslate#5]
Every so often I need to change the value of a key. Usually it's a better message or I need to completely change a label. Right now, if I make a change I update the English translation file then delete that key from 14 other language files. It's a bit tedious.

Would would be nice is the ability to re-translate just one key. 

I don't want to regenerate all the translation files because I've made some manual changes and don't want to lose them.

Thanks for making this great tool!

**Comment by leolabs** [comment]
Hey @djensen47,
would the `-d` or `--delete-unused-strings` flag do what you need? It deletes all translations that don't exist in the source language anymore.

**Comment by djensen47** [comment]
So I would do the following?

1. Delete the key from the source file
2. Run `json-autotranslate` with `-d`
3. Add the key back with a  new value
4. Run `json-autotranslate` again

**Comment by leolabs** [comment]
You can combine steps 1 and 3, so you just

1. Delete the old key and add the new one
2. Run `json-autotranslate` with the `-d` flag

This will translate the new key and delete the old one from translated files :)

**Comment by djensen47** [comment]
I wouldn't be able to do that since it's the same key. I'm updating the value.

For instance, I'm doing something like this:

```
{ "welcome": "Welcome!" }
```

```
{ "welcome": "Welcome to our app!" }
`````

**Comment by leolabs** [comment]
Ah, I was assuming you were using a Natural Language format. In your case, the process you described would do the job.

**Comment by leolabs** [comment]
I'll close this ticket for now. If you have any further questions, feel free to re-open it :)
