### ISSUE TITLE
Translations written to en.json

### ISSUE THREAD

**Issue by sr258** [leolabs/json-autotranslate#52]
So far json-autotranslate has always worked fine for me. I now suddenly get a weird error: When I run it, it translated as expected but all changes are written into en.json and not the actual locales.

I start it like this:
`json-autotranslate -d --directory-structure ngx-translate -c google_translate.json -s google-translate --decode-escapes -t key-based -i locales/lumi -m i18next`

The logs show that the direction is fine: 
`💬 Translating strings from en to de...
 (66 changes from cache)Lower case: en`

But all the German strings are written to the en.json file.

I use version 1.9.0.

**Comment by leolabs** [comment]
Hey Sebastian! Could you check whether this happens on older versions as well? If so, maybe Google's API has changed, otherwise that sounds like a bug :)

**Comment by sr258** [comment]
I've tried it with 1.8.0 and there everything works fine. With 1.9.0 I get the bug.

**Comment by leolabs** [comment]
I've reverted the change in v1.9.2, it should work as expected again now :)
