### ISSUE TITLE
i want use azure service

### ISSUE THREAD

**Issue by johnfelipe** [leolabs/json-autotranslate#67]
root@ubuntu21:~/json-autotranslate# npx json-autotranslate

	An error has occurred:
	The source language en doesn't exist.
	Error: The source language en doesn't exist.
		at /root/json-autotranslate/node_modules/json-autotranslate/lib/index.js:129:31
		at step (/root/json-autotranslate/node_modules/json-autotranslate/lib/index.js:68:23)
		at Object.next (/root/json-autotranslate/node_modules/json-autotranslate/lib/index.js:49:53)
		at /root/json-autotranslate/node_modules/json-autotranslate/lib/index.js:43:71
		at new Promise (<anonymous>)
		at __awaiter (/root/json-autotranslate/node_modules/json-autotranslate/lib/index.js:39:12)
		at translate (/root/json-autotranslate/node_modules/json-autotranslate/lib/index.js:115:12)
		at Object.<anonymous> (/root/json-autotranslate/node_modules/json-autotranslate/lib/index.js:345:1)
		at Module._compile (node:internal/modules/cjs/loader:1105:14)
		at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

how solve this?

**Comment by johnfelipe** [comment]
root@ubuntu21:~/json-autotranslate# npx json-autotranslate -i /root/json-autotranslate/src/locales/i18n -s azure -c xxxxxxxxxxxxxxxxxxx
	Found 0 target language(s):
	->

	🏭 Loading source files...
	├── admin.json (key-based)
	├── common.json (key-based)
	├── editor.json (key-based)
	├── social.json (key-based)
	├── user.json (key-based)
	└── Done

	✨ Initializing Azure...
	└── Done

	🔍 Looking for key-value inconsistencies in source files...
	└── No inconsistencies found

	🔍 Looking for invalid keys in source files...
	└── No invalid keys found

	🗂 Caching source translation files...
	└── Translation files have been cached.

	0 new translations have been added!

where put new translated json files?

**Comment by johnfelipe** [comment]
root@ubuntu21:~/json-autotranslate# npx json-autotranslate -i locales -s azure -c xxxxxx -m i18next
	Found 1 target language(s):
	-> fr

	🏭 Loading source files...
	├── admin.json (key-based)
	├── common.json (key-based)
	├── editor.json (key-based)
	├── social.json (key-based)
	├── user.json (key-based)
	└── Done

	✨ Initializing Azure...
	└── Done

	🔍 Looking for key-value inconsistencies in source files...
	└── No inconsistencies found

	🔍 Looking for invalid keys in source files...
	└── No invalid keys found

	💬 Translating strings from en to fr...
	├── Translating admin.json (0 changes from cache)
	An error has occurred:
	Azure Translation failed: {"error":{"code":401000,"message":"The request is not authorized because credentials are missing or invalid."}}
	Error: Azure Translation failed: {"error":{"code":401000,"message":"The request is not authorized because credentials are missing or invalid."}}
		at AzureTranslator.<anonymous> (/root/json-autotranslate/node_modules/json-autotranslate/lib/services/azure-translator.js:128:35)
		at step (/root/json-autotranslate/node_modules/json-autotranslate/lib/services/azure-translator.js:33:23)
		at Object.next (/root/json-autotranslate/node_modules/json-autotranslate/lib/services/azure-translator.js:14:53)
		at fulfilled (/root/json-autotranslate/node_modules/json-autotranslate/lib/services/azure-translator.js:5:58)
		at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by leolabs** [comment]
Hey @johnfelipe,

I haven't used Azure in a while, but you might have to specify a region in addition to the API key, e.g. `-c xxxxxxxxx,eastus`

Let me know if this works :)

**Comment by johnfelipe** [comment]
root@ubuntu21:~/json-autotranslate# npx json-autotranslate -i locales -s azure -c xxxxxxxx,eastus -m i18next
	Found 1 target language(s):
	-> fr

	🏭 Loading source files...
	├── admin.json (key-based)
	├── common.json (key-based)
	├── editor.json (key-based)
	├── social.json (key-based)
	├── user.json (key-based)
	└── Done

	✨ Initializing Azure...
	└── Done

	🔍 Looking for key-value inconsistencies in source files...
	└── No inconsistencies found

	🔍 Looking for invalid keys in source files...
	└── No invalid keys found

	💬 Translating strings from en to fr...
	├── Translating admin.json (0 changes from cache) (+330)
	├── Translating common.json (0 changes from cache) (+62)
	├── Translating editor.json (0 changes from cache) (+558)
	├── Translating social.json (0 changes from cache) (+156)
	├── Translating user.json (0 changes from cache) (+253)
	└── All strings have been translated.

	🗂 Caching source translation files...
	└── Translation files have been cached.

	1359 new translations have been added!
works tnks

**Comment by leolabs** [comment]
Perfect, you're welcome!
