### ISSUE TITLE
Google translate | losing interpolations

### ISSUE THREAD

**Issue by savvakis** [leolabs/json-autotranslate#7]
Hey @leolabs !

Nice library and thanks for this!
I noticed that upon translating with i18-next format & using google-translate service, the interpolations at the end were not added back after the translation and this is because Google service translates <0 /> <1 /> etc to: `&lt; 0 &gt;` so you are not able to correcty replace them back again. I assume this is probably due to invalid html nodes? Maybe this change to the service happened later on.

I tested it locally and seems to work if you just change the xmlStyleReplacer to  `<br className="${index}" />` for example.
https://github.com/leolabs/json-autotranslate/blob/cb6c9f69af0122ef13f6e89585dfa46a6cfaa03d/src/matchers/index.ts#L5

Cheers!

**Comment by leolabs** [comment]
Hey @savvakis,

I tried to reproduce your scenario but couldn't get the same issue you experienced. I created a JSON locale file with the following content:

```json
{
  "This is a {test}": "This is a {test}"
}
```

json-autotranslate translated it from English to German, Spanish, Italian, Polish, Turkish and Japanese and it all worked flawlessly. For the translation, I used the following command:

```shell
$ json-autotranslate -c service-account.json -i static/locales -s google-translate
```

Could you try to create a minimal reproducible scenario where the issue you mentioned occurs?

**Comment by leolabs** [comment]
Quick update, I noticed some regex in the i18next matcher was not correct, so I fixed that in 7e8c881. I don't know if that'd fix your problem though.

**Comment by savvakis** [comment]
Hey @leolabs ,

im using:
`json-autotranslate -t key-based -i app/locales -m i18next -s google-translate -l en`
i was not able to reproduce it outside my project which means that this might be sth else but again looks weird. Sorry i don't have more time to test it.

All i know is that i can always reproduce it in my project. Looks like some kind of encoding issue.
Never mind, in case someone else stucks on it may find the solution here.

example with:
`export const xmlStyleReplacer = (index: number) => <br class="${index}" />;`
output:
`<em><br class=\"0\" /></em> <span>werden für`

example with:
`export const xmlStyleReplacer = (index: number) => <${index} />;`
output:
`<em>&lt;0 /&gt;</em> <span>wird für`

**Comment by leolabs** [comment]
Thanks for the feedback! Does the problem you're describing happen for every translated string or are there just some specific strings where the result is faulty?

**Comment by leolabs** [comment]
I just replaced the default `<0 />` syntax with a span tag (`<span>0</span>`). This seems to solve most problems. However, different translation services behave differently here.

I'll close this issue for now, but please feel free to re-open it should you experience those problems again :)
