### ISSUE TITLE
how solve this issue about new type of json for autotranslate?

### ISSUE THREAD

**Issue by johnfelipe** [leolabs/json-autotranslate#76]
https://gist.github.com/ab1bc793fd801ebf3c125520229f0584

```
🔍 Looking for key-value inconsistencies in source files...
├── en.json contains 459 inconsistent key(s)
└── Found key-value inconsistencies in 1 file(s).
```

**Comment by jaspisus** [comment]
I have same problem, my keys in source JSON file have periods, and json-autotranslate refuses to process it.

**Comment by leolabs** [comment]
I think I found a fix for this and just pushed a new version. Let me know if this fixes the issue on your end as well :)
