### ISSUE TITLE
REQUEST: XML, YML, JS autotranslate

### ISSUE THREAD

**Issue by johnfelipe** [leolabs/json-autotranslate#77]
i hope have you a little of my time for create version for xml, yml and js instead json
Greetings

**Comment by leolabs** [comment]
Unfortunately, I don't think I'll find the time to do this, but maybe there are alternative tools out there that can do what you need.

**Comment by johnfelipe** [comment]
Can u referred?

**Comment by leolabs** [comment]
This might do what you need: https://github.com/fkirc/attranslate

**Comment by johnfelipe** [comment]
attranslate --srcFile=i18n/en.json --srcLng=en --srcFormat=nested-json
--targetFile=i18n/es.json --targetLng=es --targetFormat=nested-json
--service=google-translate
--serviceConfig=traducciones-352415-79659df1c6f1.json

waw your suggestion was great using google, tnks

but pls update your app for use watson IBM, because attranslate havent...
