### ISSUE TITLE
How to pass Google Translate API key in --config

### ISSUE THREAD

**Issue by jaspisus** [leolabs/json-autotranslate#79]
I'm running the command: npx json-autotranslate --type keybased --matcher i18next --input locales --config locales/key.json

and I'm getting an error: "key must be a string, a buffer or an object". I have API key from Google Cloud and I don't know how to pass it to json-autotranslate. How my config JSON file should look like?

**Comment by leolabs** [comment]
Your approach sounds alright, I'll try to reproduce this issue on my side.

In the meantime, could you try to set the key location via an environment variable and see if that works? For example:

```
GOOGLE_APPLICATION_CREDENTIALS=locales/key.json npx json-autotranslate --type keybased --matcher i18next --input locales
```

**Comment by jaspisus** [comment]
Thank's for reply. It's working with both approaches, but your approach gave me new error, which helped me solve the issue on Google Cloud side

**Comment by leolabs** [comment]
That's great to hear, glad it works now 👍
