### ISSUE TITLE
ICU Plurals Support fix 

### ISSUE THREAD

**Issue by Georgegriff** [leolabs/json-autotranslate#86]
Hey, first off this project is straight up 🔥  I'm really hoping to be able leverage it to help kick off internationalisation with the product that I work on.

I notice this project does not currently support plurals for ICU e.g.

```
{value, plural, =0 {No unread messages} one {{value} unread message} other {{value} unread messages} }
```

I've given a shot at adding support in the fork below. Is this something you'd be interested in me opening a PR for?
Some of the code/types may need tidying up, happy to receive pointers once/if get to PR stage

https://github.com/leolabs/json-autotranslate/compare/master...Georgegriff:json-autotranslate:icu-plurals-support?expand=1

This change will mean that "No unread messages" "unread message" and "unread messages" would be sent to be translated instead of just all placeholdered

**Comment by leolabs** [comment]
That sounds great, I'm happy to merge your PR into the project when it's ready :)

**Comment by Georgegriff** [comment]
Awesome! I'll look at getting a pr up and ready after the weekend
