### ISSUE TITLE
How to handle input keys with "." in names

### ISSUE THREAD

**Issue by Georgegriff** [leolabs/json-autotranslate#92]
I have some strings to translate which have the following structure:

```json
{
  "path.to.Component.yourProgress": {
    "defaultMessage": "Your progress"
  },
}
```

I'm finding that by default the library is unflattening my object, i suspect because internally flattenjs uses the same character for splitting objects

example output ends up breaking my json input:

```json
{
"path": {
  "to": {
    "Component": {
      "yourProgress": {
             "defaultMessage": "Your progress"
         }
    }
  }
}
}
```

Ideally the library wouldn't transform the JSON is there some way to fix this, or might have i have to flatten the files myself?

**Comment by leolabs** [comment]
I just checked if there's an easy way to tell flattenjs to use another separator but it doesn't seem that way. I'll see if I can replace the library with one that has more features, but in the meantime you could either run [flat](https://github.com/hughsk/flat) after json-autotranslate or replace your delimiters with another character, depending on what's easier for you.

**Comment by Georgegriff** [comment]
Thanks for checking! We'll find a workaround in the meantime
