### ISSUE TITLE
What are inconsistencies?

### ISSUE THREAD

**Issue by steventilator** [leolabs/json-autotranslate#96]
I have trouble understanding the concept behind "inconsistencies" mentioned here: https://github.com/leolabs/json-autotranslate#natural-language

I have a `de.json` file with key-value pairs like this:

```
"What's your name?": "Wie heisst du?"
```

When running `json-autotranslate` this gets flagged as a "key-value inconsistency".

If I then pass the `-f` flag to fix inconsistencies, my German translation file is changed to:

```
"What's your name?": "What's your name?"
```

What is the reasoning behind this? In the end, I want my German translation file to contain the English translation as the key and the German translation as the value. I also want the strings which I have already translated to be preserved.

How can I achieve this?

**Comment by steventilator** [comment]
Is it because json-autotranslate picks up multiple source files?

```
Found 3 target language(s):
-> de, fr, it

🏭 Loading source files...
├── de.json (natural)
├── en.json (natural)
├── fr.json (natural)
├── it.json (natural)
└── Done
```

I assume that only `en.json` should be picked up as a source file. How can I do this?

Currently, I call it like this:

```
json-autotranslate -i ./translations -l en -d -m i18next --directory-structure ngx-translate -s deepl-free -c [TOKEN]
```

**Comment by leolabs** [comment]
Hmm, that sounds like a bug. Usually, with the `ngx-translate` mode, the file structure you use should be supported. I'm not sure when I'll have the time to fix this, but in the meantime, you could try to use the default folder structure instead, e.g.

```
en/
  locales.json
de/
  locales.json
```

I hope this helps and will let you know once I know more about the issue.

**Comment by steventilator** [comment]
Thanks for your reply. Switching to the default folder structure helped.

However, it brought about a new issue. It seems to translate every key of the JSON. Even those which are already translated. This leads to an error because the DeepL Free API times out:

```
Found 3 target language(s):
-> de, fr, it

🏭 Loading source files...
├── en.json (natural)
└── Done

✨ Initializing DeepL Free...
└── Done

🔍 Looking for key-value inconsistencies in source files...
└── No inconsistencies found

🔍 Looking for invalid keys in source files...
└── No invalid keys found

💬 Translating strings from en to de...
├── Translating en.json

An error has occurred:
request to https://api-free.deepl.com/v2/translate?text=Exceeds+overtime+maximum&source_lang=EN&target_lang=DE&auth_key=[redacted]&formality=less failed, reason: connect ETIMEDOUT 172.65.205.19:443

FetchError: request to https://api-free.deepl.com/v2/translate?text=Exceeds+overtime+maximum&source_lang=EN&target_lang=DE&auth_key=[redacted]&formality=less failed, reason: connect ETIMEDOUT 172.65.205.19:443
    at ClientRequest.<anonymous>
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Can I set it up in a way so that only keys which are missing in the target language are translated? 

I am under the impression that already existing keys should be removed from the keys to be translated here: https://github.com/leolabs/json-autotranslate/blob/master/src/index.ts#L435-L444

**Comment by leolabs** [comment]
The tool should ignore strings that have already been translated, that's correct. Does your `de` file have a translation for "Exceeds overtime maximum" already? If so, has the tool already created a .json-autotranslate-cache folder? You could try to remove that if it exists and then try again.

From the error text, it looks like the API was down, hence the ETIMEDOUT error. I haven't found any status page for the API unfortunately, so I don't know if they were experiencing issues yesterday, unfortunately.

**Comment by steventilator** [comment]
I was able to make it work. The problem was that my translation files were named like the folder they were in. That caused problems.

**Does not work:**

```
translations/en/en.json
translations/de/de.json
translations/fr/fr.json
translations/it/it.json
```

**Works:**

```
translations/en/common.json
translations/de/common.json
translations/fr/common.json
translations/it/common.json

```

Maybe worth adding to the documentation.

Thanks for your help!

**Comment by leolabs** [comment]
That's great to hear, thank you for letting me know!
