### ISSUE TITLE
Wrong output structure

### ISSUE THREAD

**Issue by do-web** [leolabs/json-autotranslate#99]
```
  "blog": {
    "post": {
      "1": {
        "title": "Test"
      }
    }
  }
```

Gets translated to a wrong structure:

```
"blog": {
    "post": [
      null,
      {
        "title": "test"
      }
    ]
  }
```

**Comment by leolabs** [comment]
Hey @do-web,

Good catch! This had to do with the way nested structures were flattened and unflattened. I've just pushed a new version that should fix this. Let me know if it works for you.
